### PR TITLE
256

### PR DESCRIPTION
**Pull request by Jeffrey-Simpson**
Update to use rules and new expected results series. 
Added request test script to send a request test message to the TestManager

---
This change is [Reviewable](https://reviewable.io/reviews/gridappsd/gridappsd-sample-app/3)

### CODE REVIEW

**Comment by craigpnnl** [comment]
Please provide a better description/ link to #256  ( GRIDAPPSD/GOSS-GridAPPS-D#256 )

**Review by craigpnnl — COMMENTED** [review]
@Jeffrey-Simpson can you see if this PR still applies.

**Comment by Jeffrey-Simpson** [comment]
Hello,
I do not think it applies any more. I will update the sample app for testing after the Events are added and the system for executing the rules is redone.
Thanks,
-Jeff

**Comment by poorva1209** [comment]
Closing this pull request as it does not apply any more.

**Pull request closed without merging**
